apiVersion: v1
kind: Service
metadata:
  name: book-service
  labels:
    app: fastapi-book-service
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: fastapi-book-service
