apiVersion: v1
kind: Service
metadata:
  name: analytics-worker
  labels:
    app: analytics-worker
spec:
  type: ClusterIP
  ports:
  - port: 8002
    targetPort: 8002
    protocol: TCP
    name: metrics
  selector:
    app: analytics-worker
