apiVersion: v1
kind: Service
metadata:
  name: celery-worker
  labels:
    app: celery-worker
spec:
  type: ClusterIP
  ports:
  - port: 8001
    targetPort: 8001
    protocol: TCP
    name: metrics
  selector:
    app: celery-worker
