apiVersion: v1
kind: Service
metadata:
  name: fastapi-gateway-service
  labels:
    app: fastapi-gateway-service
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: web
    nodePort: 30080
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: traefik
    nodePort: 30081
  selector:
    app: fastapi-gateway-service
