apiVersion: v1
kind: Service
metadata:
  name: fastapi-gateway
  labels:
    app: fastapi-gateway
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: fastapi-gateway
